name: Build and Release HTProxy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build binaries for Linux, Windows, macOS, and Linux ARM64
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Go mod tidy
        run: go mod tidy

      # Build binaries
      - name: Build Linux binary (x64)
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o htproxy-linux-amd64

      - name: Build Linux ARM64 binary
        run: CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o htproxy-linux-arm64

      - name: Build Windows binary (x64)
        run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o htproxy-windows-amd64.exe

      - name: Build macOS binary (x64)
        run: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o htproxy-darwin-amd64

      # Set version based on date and time (Use Environment Files)
      - name: Set version based on date and time
        run: echo "VERSION=v$(date +'%y%m%d.%H%M')" >> $GITHUB_ENV

      # Create a new GitHub release using softprops/action-gh-release
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: "Release ${{ env.VERSION }}"
          files: |
            htproxy-linux-amd64
            htproxy-linux-arm64
            htproxy-windows-amd64.exe
            htproxy-darwin-amd64
